import { Button, Space } from 'antd'
import type { NextPage } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const router = useRouter()
  const handleClick = (key: string) => router.push(key)

  return (
    <div className={styles.container}>
      <Head>
        <title>Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Space size={30}>
        <Button type='primary'>HOME</Button>
        <Button type='primary' onClick={() => handleClick('/admin')}>Admin</Button>
        <Button type='primary' onClick={() => handleClick('/products')}>product-detial</Button>
        <Button type='primary' onClick={() => handleClick('/checkout')}>checkout</Button>
        <Button type='primary' onClick={() => handleClick('/payment')}>payment</Button>
        <Button type='primary' onClick={() => handleClick('/brands')}>brands</Button>
        <Button type='primary' onClick={() => handleClick('/categories')}>categories</Button>
        <Button type='primary' onClick={() => handleClick('/promotion')}>promotion</Button>

      </Space>

    </div>
  )
}

export default Home
